name: 24/7 Telegram Bot

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install python-telegram-bot[job-queue]==20.3
          pip install python-dotenv==0.21.0
          
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
        run: python bot.py
