name: Advanced Bot Deployment

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
        run: python bot.py
