name: Telegram Bot Runner
on:
  workflow_dispatch:  # يسمح بالتشغيل اليدوي
  push:
    branches: [ main ]  # التشغيل عند أي push
  schedule:
    - cron: "*/5 * * * *"  # كل 5 دقائق

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python bot.py
